{% set version = "1.5" %}

package:
  name: jq
  version: {{ version }}

source:
  fn: jq-{{ version }}.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-{{ version }}/jq-{{ version }}.tar.gz
  md5: 0933532b086bd8b6a41c1b162b1731f9

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - oniguruma 6.8.*
  run:
    - oniguruma 6.8.*

test:
  commands:
    - jq --help  # [not win]

about:
  home: http://stedolan.github.io/jq/
  license: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
