{% set version = "1.5" %}

package:
  name: jq
  version: {{ version }}

source:
  fn: jq-{{ version }}.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-{{ version }}/jq-{{ version }}.tar.gz
  sha256: c4d2bfec6436341113419debf479d833692cc5cdab7eb0326b5a4d4fbe9f493c

build:
  number: 1005
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - oniguruma 6.8.*
  run:
    - oniguruma 6.8.*

test:
  commands:
    - jq --help  # [not win]

about:
  home: http://stedolan.github.io/jq/
  license: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
