# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MTAO0xXjsWxmEHkKw0ZY3htNttw2mp+scfmF3m+ORcn1op7gz6/mxu8a1MHHatWAwUjq5JRUVWQ6fManKqcAxGW+vbOOub9eg2FULWYZsYMECWT3i/uCLAOXB2lLBEc6+FbC2bctQA5FdBhWpFOhECagLI8bNEyQNBv5IfRmuzFqIFIY5DXORkFCfnbc1yaLwWiE2VhZdrEBPdJepoiI3dfOOoQRiOM3BanSOKkO/bfGnA0b1kbBTX3s6RvsUWYxWz7p21NPB8hMFvFa9LayimHYepNYpC5uSq4HITDGHA8NTOWmrTCF9b4zoZLFFS1AaUZpP261vRqB76VhOfokBHAVRUI40U82CEBHbOtgEPs1plgDa0fEn9gPn3U4N1QbAt2C9Fi2oUiSawh/Swu2nq/o3tMiAghD8RG2/VIznC6i/sydaz2JAkhYG0izQw/Hymp0SbnweF+N6E8stemyus9zOxgN7Y2DfMoMpXZ/yf7OXKvMonbuIXMypTQVGdS74J/FLeMbChyS3G1f5s4CbUkBCjFuETCuPmMcHHezffXq3rYOiNYSSdw9/4zqEhUSK18a+Wa+clipNG9YfUkXBEWePUrxg7gbMYUhPduQUSwMc5Ld02O1aRYlT9GYXVOSVcrVLgU5W3izmIAc6ifwmjLPKi1LKZ02ttIjcEBjOEw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
