# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HWqGc7yLDobrK6j5pa5a2FtS4qZtV6fwNqc99RPUOfhA77qPqI4+rtHB8RaG4G/DTDYrOdaNcgT+PpDqf/WI/AisCA57AM0qBWJjtrSMrd7HWL1fsZ2jJK/v5lDOum2un+cfcAKnduhwEtu2AK8NEKq7TfJo53tQ0r648kzjOUeijN2shPqrChtXH8NdDujhemSahYIkpi3Dn9L0H2yTAo8MwwHF8xrDp72oB+r2RzgBO752jLjl6RtqOUYIp63O7zuLSK6FIGkzqG+wmAcMcHcACnbQO6c1iCz8BBswF9FFQVyCBBN4BbrIF3AVNAqF6bt+jKosEA6KSI7Z3XHN6GI1CtjA6SLhi4Fcsql4Fn29LgdEFY0RewZxN1xHvFzjkzvQThLaEPXc1KezZWcJuZ5qsI2SJ9S+6Vrf9oB2OQjYrSQXt5S9OUQFLLFmQdEZE/48iEHhLB/rYVX4P/6BUbBSVL76LWsp6pVErMcxVNSbTtmeyqxlafU5xmvPl8H5hLrtV/pyk/bAhpA18VQNfV2pRh4v3xtp98tQNwxDa2Q4M43tf8pH7kFK0+PNbJE+IKB5p6qoMU4EmDDaUislHeXmF+uwmMQfnM6bRExu20PEuGay0pRcFqDw5v8hbSc2/MbwcBYV3PI8EAFXK7DfY9KcvlUi7C7ujfOyYBqmcnQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml