travis:
  secure:
    BINSTAR_TOKEN: HbO01ghWFTZ9+a7MHDF2IomOGXcRqCpYeQgMGPs/D8ejbA5l1Pz5MqAVxa73SV9yX+CdnOlsQI62O9nuwXfenULrl8pv446nR4rfEEweib2qzYBZlU6NLngV7WPwgBfJ2AaamSlrBZA15A4Id3yY2ZLqtK7iHnYGWm3DoAMDu+aXf4v7uuGC/6P7zzjOF2443V522ElGEjElq+4/TWQZ9vTmDglEgbNwI2cB5SE3KqMm0im2VYLbg9gueTZTp6p99HlElt6MvSqLE3LsbRjB4VeXnK4rXfzelZ24xIjoNB5JCEx+i9PxrB/keTKSx3oLfuMDcnhtD3TSLqCu7hyAALadeXjqdqdFFKNpSHBsDgozvNpAUIlKD3BIyVCumChACmv5PFPCh3B+hM9G7JrhykwJYO6YM3GlIThUr8omYAbyjCgV/RHV93aUYyatKvbKWgUefOfcJFS0ym5EDi5mtM/4R+hDyLyi0jH12fAJ/rF8dphMhhaZPwzRf7Db0RkQ9FjpB6bgV4vKSW5gFd0ly/tKSXQ5ToiaXOf2HueGKuMeiHtSalEOvUPtUwnz2iWqRylIXo2xdvhKIE7KPwIGBQmOn+1VmLe8gPvK/ExwXiKvDLKIkyIg27wNRVpn8pDBkiaI4h8uNgZKnPzRfUpT+YwfWj8p6IO4EewX/0Ul3Ps=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
