travis:
  secure:
    BINSTAR_TOKEN: MTAO0xXjsWxmEHkKw0ZY3htNttw2mp+scfmF3m+ORcn1op7gz6/mxu8a1MHHatWAwUjq5JRUVWQ6fManKqcAxGW+vbOOub9eg2FULWYZsYMECWT3i/uCLAOXB2lLBEc6+FbC2bctQA5FdBhWpFOhECagLI8bNEyQNBv5IfRmuzFqIFIY5DXORkFCfnbc1yaLwWiE2VhZdrEBPdJepoiI3dfOOoQRiOM3BanSOKkO/bfGnA0b1kbBTX3s6RvsUWYxWz7p21NPB8hMFvFa9LayimHYepNYpC5uSq4HITDGHA8NTOWmrTCF9b4zoZLFFS1AaUZpP261vRqB76VhOfokBHAVRUI40U82CEBHbOtgEPs1plgDa0fEn9gPn3U4N1QbAt2C9Fi2oUiSawh/Swu2nq/o3tMiAghD8RG2/VIznC6i/sydaz2JAkhYG0izQw/Hymp0SbnweF+N6E8stemyus9zOxgN7Y2DfMoMpXZ/yf7OXKvMonbuIXMypTQVGdS74J/FLeMbChyS3G1f5s4CbUkBCjFuETCuPmMcHHezffXq3rYOiNYSSdw9/4zqEhUSK18a+Wa+clipNG9YfUkXBEWePUrxg7gbMYUhPduQUSwMc5Ld02O1aRYlT9GYXVOSVcrVLgU5W3izmIAc6ifwmjLPKi1LKZ02ttIjcEBjOEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
